name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

########################################################################
## CONFIGURATION
########################################################################

env:
  IDRIS2_COMMIT: 768d164ec9cf37638f7604ee3a22de2aabfc6852
  SCHEME: scheme

jobs:
  ubuntu-chez:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise variables
        run: |
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH

      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ~/.idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}-scheme954

      - name: Install Chez
        run: |
          echo "deb http://security.ubuntu.com/ubuntu hirsute universe" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y -t hirsute chezscheme

      - name: Test Scheme
        run: |
          scheme --version

      - name: Install Idris2
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          make bootstrap && make install

      - name: Install idris2-elab-util
        run: |
          git clone https://github.com/stefan-hoeck/idris2-elab-util
          cd idris2-elab-util
          make install

      - name: Install idris2-sop
        run: |
          git clone https://github.com/stefan-hoeck/idris2-sop
          cd idris2-sop
          make install

      - name: Install idris2-tls
        run: |
          git clone https://github.com/octeep/idris2-tls.git
          cd idris2-tls
          make install
        shell: bash

      - name: Checkout idris2-http
        uses: actions/checkout@v2

      - name: Build package
        run: make install

      - name: Test package
        run: make test

  windows-chez:
    runs-on: windows-latest
    env:
      MSYSTEM: MINGW64
      MSYS2_PATH_TYPE: inherit
      SCHEME: scheme
      CC: gcc
    steps:
      - name: Init
        run: |
          git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ChezScheme
            .idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}
      - name: Get Chez Scheme
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 https://github.com/cisco/ChezScheme
          c:\msys64\usr\bin\bash -l -c "pacman -S --noconfirm tar make"
          echo "PWD=$(c:\msys64\usr\bin\cygpath -u $(pwd))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Configure and Build Chez Scheme
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          c:\msys64\usr\bin\bash -l -c "cd $env:PWD && cd ChezScheme && ./configure --threads && make"
      - name: Set Path
        run: |
          $chez="$(pwd)\ChezScheme\ta6nt\bin\ta6nt"
          $idris="$(pwd)\.idris2"
          echo "$chez" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "$idris\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "IDRIS_PREFIX=$idris" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "PREFIX=$(c:\msys64\usr\bin\cygpath -u $idris)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Test Scheme
        run: |
          scheme --version
      - name: Install Idris2
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          c:\msys64\usr\bin\bash -l -c "cd $env:PWD && cd idris2 && make bootstrap && make install"
      - name: Install idris2-elab-util
        run: |
          git clone https://github.com/stefan-hoeck/idris2-elab-util
          cd idris2-elab-util
          make install

      - name: Install idris2-sop
        run: |
          git clone https://github.com/stefan-hoeck/idris2-sop
          cd idris2-sop
          make install

      - name: Install idris2-tls
        run: |
          git clone https://github.com/octeep/idris2-tls.git
          cd idris2-tls
          make install
        shell: bash

      - name: Checkout idris2-http
        uses: actions/checkout@v2
        with:
          path: http

      - name: Build package
        run: |
          cd http
          echo "HTTPPATH=$(c:\msys64\usr\bin\cygpath -u $(pwd))" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          make install

      - name: Test package
        run: c:\msys64\usr\bin\bash -l -c "cd $env:HTTPPATH && make test"

  macos-chez:
    runs-on: macos-latest
    env:
      SCHEME: chez
    steps:
      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ~/.idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}

      - name: Install Idris2 build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "$HOME/.idris2/bin" >> "$GITHUB_PATH"

      - name: Build Idris 2 from bootstrap
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          chmod -R a-w bootstrap
          make bootstrap && make install
        shell: bash

      - name: Install idris2-elab-util
        run: |
          git clone https://github.com/stefan-hoeck/idris2-elab-util
          cd idris2-elab-util
          make install
        shell: bash

      - name: Install idris2-sop
        run: |
          git clone https://github.com/stefan-hoeck/idris2-sop
          cd idris2-sop
          make install
        shell: bash

      - name: Install idris2-tls
        run: |
          git clone https://github.com/octeep/idris2-tls.git
          cd idris2-tls
          make install
        shell: bash

      - name: Checkout idris2-http
        uses: actions/checkout@v2
        with:
          path: http

      - name: Build package
        run: |
          cd http
          make install

      - name: Test package
        run: |
          cd http
          make test
