name: Build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

########################################################################
## CONFIGURATION
########################################################################

env:
  IDRIS2_COMMIT: 768d164ec9cf37638f7604ee3a22de2aabfc6852
  SCHEME: scheme

jobs:
  ubuntu-chez:
    runs-on: ubuntu-latest
    steps:
      - name: Initialise variables
        run: |
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH

      # This caching step allows us to save a lot of building time by only
      # rebuilding Idris2 from boostrap if absolutely necessary
      - name: Cache Idris2
        uses: actions/cache@v2
        id: cache-idris2
        with:
          path: |
            ~/.idris2
          key: ${{ runner.os }}-${{ env.IDRIS2_COMMIT }}-scheme954

      - name: Install Chez
        run: |
          echo "deb http://security.ubuntu.com/ubuntu hirsute universe" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y -t hirsute chezscheme

      - name: Test Scheme
        run: |
          scheme --version

      - name: Install Idris2
        if: steps.cache-idris2.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/idris-lang/idris2
          cd idris2
          git checkout ${{ env.IDRIS2_COMMIT }}
          make bootstrap && make install

      - name: Install idris2-elab-util
        run: |
          git clone https://github.com/stefan-hoeck/idris2-elab-util
          cd idris2-elab-util
          make install

      - name: Install idris2-sop
        run: |
          git clone https://github.com/stefan-hoeck/idris2-sop
          cd idris2-sop
          make install

      - name: Install idris2-tls
        run: |
          git clone https://github.com/octeep/idris2-tls.git
          cd idris2-tls
          make install
        shell: bash

      - name: Checkout idris2-http
        uses: actions/checkout@v2

      - name: Build package
        run: make install

      - name: Test package
        run: make test
